version: '3'

services:
  kakeibot:
    build: .
    env_file:
      - .env
    depends_on:
      - db  # アプリケーションがdbに依存することを示す
    networks:
      - app-network

  db:  # MySQLのサービス定義
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql  # 永続的なデータボリュームを使用
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
